---

# external
app_servername : "{{ app_servername }}"

# app
prefix      : /opt/graphite
app_conf    : "{{ prefix }}/conf"
app_log     : "{{ prefix }}/log"

# admin user
admin_user  : admin
admin_email : dev.aert@gmail.com
admin_pwd   : admin
