---

# Dependencies
- name: graphite.apt
  apt: pkg={{ item }} state=installed
  with_items:
    - python-pip
    - python-dev
    - supervisor


- name: graphite.whisper
  pip: name=whisper version=0.9.12

- name: graphite.carbon.daemonize
  pip: name=daemonize version=2.2.1

- name: graphite.carbon.twisted
  pip: name=Twisted version=11.1.0

- name: graphite.carbon
  pip: name=carbon version=0.9.12

- name: graphite.web.django
  pip: name=django version=1.6

- name: graphite.web.django-tagging
  pip: name=django-tagging version=0.3.1

- name: graphite.web
  pip: name=graphite-web version=0.9.12

