---

- name: supervisor.start
  shell: service supervisor start

- name: supervisor.conf
  template: src=supervisor.conf dest=/etc/supervisor/conf.d/graphite.conf
  notify:
    - restart supervisor
    - restart nginx

